FROM maven:3.5-jdk-8
RUN mkdir -p /src
COPY . /src
WORKDIR /src
RUN mvn package

FROM java:8-alpine
RUN mkdir -p /app
COPY --from=0 /src/target/demo-0.0.1-SNAPSHOT.jar /app/myapp.jar
WORKDIR /app
EXPOSE 9000
ENTRYPOINT [ "java", "-Dserver.port=9000", "-jar", "/app/myapp.jar" ]
