FROM ubuntu:16.10

# expensive commands first
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  python3 \
  && rm -rf /var/lib/apt/lists/*

COPY static/ /src

WORKDIR /src

ENV PORT 8080

EXPOSE $PORT

# defines an executable command in shell form
ENTRYPOINT python3 -m http.server $PORT